apiVersion: batch/v1
kind: Job
metadata:
  name: querybook-job
  labels:
    app: querybook-job

# The traderepository frontend replica set ensures that at least 3
# instances of the traderepository app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  completions: 10
  parallelism: 10
  template:
    spec:
      containers:
      - name: querybook
        # Replace [GCLOUD_PROJECT] with your project ID.
        image: gcr.io/fo-ods/traderepository:v7
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        args: ["java", "-cp", "app.jar", "foods.bigtable.loadtest.QueryTester", "fo-ods", "repository-test", "foods.bigtable.loadtest.QueryBookTester", "10000", "20"]
        env:
        - name: JAVA_HEAP_OPTS
          value: "-Xmx400m -Xms200m"
        - name: JAVA_USER_OPTS
          #value: "-XX:+PrintFlagsFinal -XX:+PrintGCDetails"
          value: "-XX:+PrintFlagsFinal"
        - name: google_bigtable_grpc_retry_max_scan_timeout_retries
          value: "1"
        - name: google_bigtable_grpc_read_partial_row_timeout_ms
          value: "3600000" # 1 hr
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
      restartPolicy: Never