apiVersion: v1
kind: Service

metadata:
  name: traderepository
  labels:
    app: traderepository

spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: grpc
  selector:
    app: traderepository

