apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traderepository
  labels:
    app: traderepository

# The traderepository frontend replica set ensures that at least 3
# instances of the traderepository app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  replicas: 3

  template:
    metadata:
      labels:
        app: traderepository

    spec:
      containers:
      - name: traderepository
        # Replace [GCLOUD_PROJECT] with your project ID.
        image: gcr.io/fo-ods/traderepository:v8

        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always

        # The traderepository process listens on port 8080 for web traffic by default.
        ports:
        - name: grpc
          containerPort: 8090
        env:
        - name: SERVICE_GRPC_PORT
          value: "8090"
        - name: PROJECT_ID
          value: fo-ods
        - name: BIGTABLE_INSTANCE_ID
          value: bigtable-test

