apiVersion: v1
kind: Service

metadata:
  name: tradecore-ult
  labels:
    app: tradecore-ult

spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: http
  selector:
    app: tradecore-ult