apiVersion: v1
kind: Service

metadata:
  name: tradecore-servicelayer
  labels:
    app: tradecore-servicelayer

spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: http
 # - port: 443
 #   targetPort: https
  selector:
    app: tradecore-servicelayer