apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eqtradecore-dlt
  labels:
    app: eqtradecore-dlt

# The traderepository frontend replica set ensures that at least 3
# instances of the traderepository app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  replicas: 4

  template:
    metadata:
      labels:
        app: eqtradecore-dlt

    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: high-cpu

      containers:
      - name: sit-eq-tradecore-lcm
        # Replace [GCLOUD_PROJECT] with your project ID.
        image: gcr.io/fo-ods/tradecore-dlt:roman

        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "400m"
          limits:
            memory: "4Gi"
            cpu: "800m"
        args: ["java", "-cp", "app.jar", "foods.dlt.stats.StatsMain"]
        env:
        - name: DLT_PUBSUB_FAILQUEUE_TOPIC
          value: "roman-dlt-eq-error"
        - name: PUBSUB_TOPIC
          value: "roman-ult-eq-sub-lcm"
        - name: INSTANCEID
          value: "tradecore-stats"
        - name: DATABASEID
          value: "statsdb-roman"
        - name: DLT_PUBSUB_SUBCRIBE
          value: "roman-dlt-eq-bbb-sub"
        - name: SIM_UPSTREAM
          value: "false"
        - name: IGNORE_ERROR
          value: "true"
        - name: SUCCESS_RATE
          value: "0.9"
        - name: DISABLE_METRIC
          value: "false"
        - name: JAVA_HEAP_OPTS
          value: "-Xmx4g -Xms2g"
