apiVersion: v1
kind: Service

metadata:
  name: sit-eq-tradecore-lcm
  labels:
    app: sit-eq-tradecore-lcm

spec:
  type: LoadBalancer
  ports:
  
  - port: 3000
    targetPort: grpc
 # - port: 443
 #   targetPort: https
  selector:
    app: sit-eq-tradecore-lcm