apiVersion: batch/v1
kind: Job
metadata:
  name: sit-ir-tradecore-balcm-client
  labels:
    app: sit-ir-tradecore-balcm-client

# The traderepository frontend replica set ensures that at least 3
# instances of the traderepository app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: sit-ir-tradecore-balcm-client
        image: gcr.io/fo-ods/tradecore-balcm-api:latest
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        args: ["java", "-cp", "apps/tradecore-balcm-0.1.0-SNAPSHOT.jar", "com.maplequad.fo.ods.tradecore.balcm.client.TradeCoreBalcmAppClient", "1000", "1","1"]
        #146.148.116.205
        #35.195.88.22  "fi-irs-ba", "104.155.10.143","3000",
        env:
        - name: RUN_NO
          value: "1"
        - name: GKE_RUN
          value: "YES"
        - name: TC_TG_ASSET_CLASS
          value: "fi-irs-ba"
        - name: TC_ASSET_CLASS
          value: "ird"
        - name: TC_STORE_SRVC_HOST
          value: "130.211.87.74"
        - name: TC_STORE_SRVC_PORT
          value: "3002"
        - name: TC_BALCM_SRVC_HOST
          value: "130.211.48.239"
        - name: TC_BALCM_SRVC_PORT
          value: "3001"
        - name: TC_BALCM_SRVC_THREADS
          value: "2"
        - name: TG_LOG_GEN
          value: "OFF"
        - name: JAVA_HEAP_OPTS
          value: "-Xmx400m -Xms200m"
        - name: JAVA_USER_OPTS
          #value: "-XX:+PrintFlagsFinal -XX:+PrintGCDetails"
          value: "-XX:+PrintFlagsFinal"
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
      restartPolicy: Never