apiVersion: v1
kind: Pod
metadata:
  name: ir-ult-pod
  labels:
    app: ir-ult

# The traderepository frontend replica set ensures that at least 3
# instances of the traderepository app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  containers:
  - name: ult
    # Replace [GCLOUD_PROJECT] with your project ID.
    image: gcr.io/fo-ods/tradecore-ult:roman
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "3Gi"
        cpu: "1500m"
    args: ["java", "-cp", "app.jar", "foods.ult.pubsub.UltMain",
           "10000", "fi-irs", "2", "2", "uat-ird-ult-feed", "5001", "1", "1400"]
    #146.148.116.205
    #35.195.88.22
    env:
    - name: JAVA_HEAP_OPTS
      value: "-Xmx2g -Xms1g"
    #- name: JAVA_USER_OPTS
      #value: "-XX:+PrintFlagsFinal -XX:+PrintGCDetails"
    #  value: "-XX:+PrintFlagsFinal"
    # This setting makes nodes pull the docker image every time before
    # starting the pod. This is useful when debugging, but should be turned
    # off in production.
    imagePullPolicy: Always
  restartPolicy: Never
