apiVersion: v1
kind: Pod
metadata:
  name: dlt-pod-roman
  labels:
    app: dlt-pod-roman

# The traderepository frontend replica set ensures that at least 3
# instances of the traderepository app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  containers:
  - name: dlt
    # Replace [GCLOUD_PROJECT] with your project ID.
    image: gcr.io/fo-ods/dlt:roman
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "1Gi"
        cpu: "1500m"
    args: ["java", "-cp", "app.jar", "foods.dlt.stats.StatsMain", "fo-ods", "stats-roman2", "tradecore-stats", "statsdb", "true"]
    env:
    - name: JAVA_HEAP_OPTS
      value: "-Xmx1g -Xms500m"
    - name: JAVA_USER_OPTS
      #value: "-XX:+PrintFlagsFinal"
      value: "-XX:+PrintFlagsFinal -XX:+PrintGCDetails"
    # This setting makes nodes pull the docker image every time before
    # starting the pod. This is useful when debugging, but should be turned
    # off in production.
    imagePullPolicy: Always
  restartPolicy: Never