apiVersion: v1
kind: Pod
metadata:
  name: tradecore-ulg
  labels:
    app: tradecore-ulg
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  containers:
  - name: tradecore-ulg
    image: gcr.io/fo-ods/fo-ods-ulg-beta
    resources:
      requests:
        memory: "300Mi"
        cpu: "200m"
      limits:
        memory: "500Mi"
        cpu: "500m"
    args: ["java", "-cp", "fo-ods-ulg-0.1.0-SNAPSHOT.jar", "com.maplequad.fo.ods.ulg.app.UpstreamLoadGen", "cash-eq", "tradecore", "100000", "5000"]
    env:
    - name: JAVA_HEAP_OPTS
      value: "-Xmx500m -Xms200m"
    - name: JAVA_USER_OPTS
      value: "-XX:+PrintFlagsFinal"
      #value: "-XX:+PrintFlagsFinal -XX:+PrintGCDetails"
    # This setting makes nodes pull the docker image every time before starting the pod.
    # This is useful when debugging, but should be turned off in production.
    imagePullPolicy: Always
  restartPolicy: Never