apiVersion: v1
kind: Service

metadata:
  name: uat-ir-tradecore-balcm
  labels:
    app: uat-ir-tradecore-balcm

spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: grpc
  selector:
    app: uat-ir-tradecore-balcm
