apiVersion: v1
kind: Pod
metadata:
  name: uat-ir-tradecore-err
  labels:
    app: uat-ir-tradecore-err

# The traderepository frontend replica set ensures that at least 3
# instances of the traderepository app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  containers:
  - name: uat-ir-tradecore-service
    # Replace [GCLOUD_PROJECT] with your project ID.
    image: eu.gcr.io/fo-ods/tradecore-failqueue:v1
    resources:
      requests:
        memory: "500Mi"
        cpu: "200m"
      limits:
        memory: "500Mi"
        cpu: "400m"
    ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 443
          protocol: TCP
    args: ["java", "-jar", "/app.jar", "uat-ir-dlt-err-sub"]
    env:
    - name: JAVA_HEAP_OPTS
      value: "-Xmx500m -Xms500m"
    - name: JAVA_USER_OPTS
      value: "-XX:+PrintFlagsFinal"
      

      #value: "-XX:+PrintFlagsFinal -XX:+PrintGCDetails"
    # This setting makes nodes pull the docker image every time before
    # starting the pod. This is useful when debugging, but should be turned
    # off in production.
    imagePullPolicy: Always
  restartPolicy: Never