apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uat-eq-tradecore-dlt
  labels:
    app: uat-eq-tradecore-dlt

# The traderepository frontend replica set ensures that at least 3
# instances of the traderepository app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: uat-eq-tradecore-dlt

    spec:
      containers:
      - name: uat-eq-tradecore-service
        # Replace [GCLOUD_PROJECT] with your project ID.
        image: gcr.io/fo-ods/tradecore-dlt:v1

        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        args: ["java", "-cp", "app.jar", "foods.dlt.stats.StatsMain", "fo-ods"]
        env:
        - name: DLT_PUBSUB_FAILQUEUE_TOPIC
          value: "uat-eq-dlt-err-sub"
        - name: PUBSUB_TOPIC
          value: "uat-eq-ult-feed"
        - name: INSTANCEID
          value: "tradecore-stats"
        - name: DATABASEID
          value: "statsdb2"
        - name: DLT_PUBSUB_SUBCRIBE
          value: "uat-eq-lcm-feed-dlt-sub"
        - name: SIM_UPSTREAM
          value: "true"
        - name: IGNORE_ERROR
          value: "true"
        - name: SUCCESS_RATE
          value: "0.9"