apiVersion: v1
kind: Service

metadata:
  name: dev-xa-tradecore-store
  labels:
    app: dev-xa-tradecore-store

spec:
  type: LoadBalancer
  ports:
  - port: 3002
    targetPort: grpc
    name: gprc
  - port : 8080
    targetPort: http
    name: http
  selector:
    app: dev-xa-tradecore-store
