apiVersion: v1
kind: Service

metadata:
  name: sit-xa-tradecore-store
  labels:
    app: sit-xa-tradecore-store

spec:
  type: LoadBalancer
  ports:
  - port: 3002
    targetPort: grpc
  selector:
    app: sit-xa-tradecore-store

